### ISSUE TITLE
想问一下师傅有没有遇到git clone 官方仓库的时候，报错找不到https仓库，明明clone的是git协议

### ISSUE THREAD

**Issue by lzxzl** [zevin02/xv6-labs-2022#2]
如题

<img width="570" alt="image" src="https://user-images.githubusercontent.com/44419594/215569388-65bd7036-b4e3-4679-98d5-79f2757f9b49.png">

**Comment by zevin02** [comment]
应该是这个仓库又移动了

**Comment by zevin02** [comment]
![截图 2023-01-31 17-49-18](https://user-images.githubusercontent.com/92536645/215726464-7108c7b9-181c-49b6-851b-c2ee4e357684.png)
我试了一下可以呀，你解决了吗

**Comment by lzxzl** [comment]
不知道是我本机的配置有问题还是系统不同的原因，我在ubuntu虚拟机上也没有问题，我先在虚拟机上操作吧。谢谢师傅

**Comment by zevin02** [comment]
好的
